version: "2.2"
services:
  web:
    build: .
    environment:
      POSTGRES_URI: "postgres://ggb:ggb@db/ggb"
      LISTEN_ADDRESS: "0.0.0.0"
      LISTEN_PORT: 8080
    depends_on:
      - db
    ports:
      - "8080:8080"
  db:
    image: postgres
    environment:
      POSTGRES_USER: ggb
      POSTGRES_PASSWORD: ggb
    ports:
      - "5432:5432"
